---
name: matrix 
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            java-version: [17,21]
        steps:
            - name: get the code
              uses: actions/checkout@v5
            - name: setup the java
              uses: actions/setup-java@v5
              with:
                java-version: 17
                distribution: temurin
            - name: check the code
              run: java --version
        